# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rodolfo Silva
email: contato@rodolfosilva.com
description: > # this means to ignore newlines until "baseurl:"
  Desenvolvedor apaixonado por novas tecnologias.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://rodolfosilva.com" # the base hostname & protocol for your site
twitter_username: Ro_DolfoSilva
github_username: RodolfoSilva
disqus_shortname: rodolfosilva

# Build settings
exclude: ['README.md']
sass:
  sass_dir: _sass
include: ['_pages']

kramdown:
  input: GFM

markdown: kramdown

gems:
  - jekyll-gist
